version: '2'
services:
  jenkins-server:
    image: jenkins:alpine
    hostname: jenkins
    container_name: jenkins
    restart: always
    environment:
     - JAVA_OPTS=-Xms512m -Xmx1024m -XX:PermSize=512m -XX:MaxPermSize=1024m -Duser.timezone=Asia/Shanghai
    volumes:
    # chown -R 1000:1000 ./data/jenkins
    - ./data/jenkins:/var/jenkins_home
    ports:
    - "8080:8080"
    - "50000:50000"
  jenkins-jnlp:
    image: jicki/jenkins-jnlp:gradle3.2
    hostname: jnlp
    container_name: jnlp
    restart: always
    environment:
     - JENKINS_URL=http://172.18.134.66:8080
     - JENKINS_AGENT_WORKDIR=/home/jenkins
     - JENKINS_AGENT_NAME=jnlp
     - JENKINS_SECRET=96fb2a610d5c67ec81c43183b0fdf4a4556de294853795a6db9e39a5d4db0295
    volumes:
    - ./data/jnlp:/home/jenkins
    - ./data/gradle:/root/.gradle
